import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import Header2 from '@/Components/Header2'
import Accesories from '@/Components/Accesories'
import ForYou from '@/containers/ForYou'





export default function Home() {
  


  return (
    <>
      <Head>
        <title>Estudio2.15</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
    
      <main className={styles.main}>
        <Header></Header>
        <Header2></Header2>
        <Accesories></Accesories>
        <ForYou title='recomendado para tí'></ForYou>
      </main>
    </>
  )
}
